Predicting if a person having certain characteristics ie categories would have diabetes or not using K-Nearest Neighbours Algorithm

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
dataset=pd.read_csv('diabetes.csv')
X = dataset.iloc[ : , : -1].values 
#independent features like pregnancies,glucose,BP,skin thickness,insulin,BMI,Diabetes Pedigree Fn,Age
y= dataset.iloc[ : , -1].values 
#dependent target output last outcome column
print(dataset)
print(X)
print(y)

      Pregnancies  Glucose  ...  Age  Outcome
0               2      138  ...   47        1
1               0       84  ...   23        0
2               0      145  ...   31        1
3               0      135  ...   24        1
4               1      139  ...   21        0
...           ...      ...  ...  ...      ...
1995            2       75  ...   33        0
1996            8      179  ...   36        1
1997            6       85  ...   42        0
1998            0      129  ...   26        1
1999            2       81  ...   25        0

[2000 rows x 9 columns]
[[2.00e+00 1.38e+02 6.20e+01 ... 3.36e+01 1.27e-01 4.70e+01]
 [0.00e+00 8.40e+01 8.20e+01 ... 3.82e+01 2.33e-01 2.30e+01]
 [0.00e+00 1.45e+02 0.00e+00 ... 4.42e+01 6.30e-01 3.10e+01]
 ...
 [6.00e+00 8.50e+01 7.80e+01 ... 3.12e+01 3.82e-01 4.20e+01]
 [0.00e+00 1.29e+02 1.10e+02 ... 6.71e+01 3.19e-01 2.60e+01]
 [2.00e+00 8.10e+01 7.20e+01 ... 3.01e+01 5.47e-01 2.50e+01]]
[1 0 1 ... 0 1 0]


In [0]:
dataset.head(10) #tells us about the column labels 

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            2      138             62  ...                     0.127   47        1
1            0       84             82  ...                     0.233   23        0
2            0      145              0  ...                     0.630   31        1
3            0      135             68  ...                     0.365   24        1
4            1      139             62  ...                     0.536   21        0
5            0      173             78  ...                     1.159   58        0
6            4       99             72  ...                     0.294   28        0
7            8      194             80  ...                     0.551   67        0
8            2       83             65  ...                     0.629   24        0
9            2       89             90  ...                     0.292   42        0

[10 rows x 9 columns]

In [0]:
dataset.tail() #tells us about the row index 

Pregnancies  Glucose  ...  Age  Outcome
1995            2       75  ...   33        0
1996            8      179  ...   36        1
1997            6       85  ...   42        0
1998            0      129  ...   26        1
1999            2       81  ...   25        0

[5 rows x 9 columns]

In [0]:
dataset.shape #tells us about the no. of rows and columns ie total no. of elements in dataset

(2000, 9)

Checking and Handling Missing values

In [0]:
dataset.isnull().sum()


Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [0]:
zero_not_accepted=['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for column in zero_not_accepted:
  dataset[column]=dataset[column].replace(0,np.NaN)
  mean=int(dataset[column].mean(skipna=True))
  dataset[column]=dataset[column].replace(np.NaN,mean)
  #dataset[column]=dataset[column].replace(np.NaN,mean(dataset[column]))
dataset

Pregnancies  Glucose  ...  Age  Outcome
0               2    138.0  ...   47        1
1               0     84.0  ...   23        0
2               0    145.0  ...   31        1
3               0    135.0  ...   24        1
4               1    139.0  ...   21        0
...           ...      ...  ...  ...      ...
1995            2     75.0  ...   33        0
1996            8    179.0  ...   36        1
1997            6     85.0  ...   42        0
1998            0    129.0  ...   26        1
1999            2     81.0  ...   25        0

[2000 rows x 9 columns]

Encoding categorical data not reqd as all columns have integer dtype value elements

Splitting dataset into training set and test set

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)

Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
ss_X = StandardScaler()
X_train = ss_X.fit_transform( X_train )
X_test = ss_X.fit_transform( X_test )
print(X_train)
print(X_test)

[[ 2.54014777 -0.01485297  0.466638   ... -0.70153446 -0.65077302
   2.50732972]
 [ 4.06518958  1.29329836  0.16097992 ...  1.04410009  1.04381097
   1.21199837]
 [-0.81494422 -0.60663571  0.26286595 ...  0.87438562 -0.5475188
   0.78022125]
 ...
 [ 0.10008087 -0.82466093 -0.24656419 ... -0.03479904 -0.94838813
  -0.16968841]
 [ 2.23513941 -1.13612553  0.26286595 ... -0.26512582 -0.52626057
   0.17573329]
 [ 0.40508923  0.45234393  0.67041006 ... -3.91398693  0.50628164
   3.11181769]]
[[-0.53716528  0.09403535 -1.29820559 ...  1.33237215  0.19573803
  -0.6048957 ]
 [-0.53716528 -0.43972122 -0.83388706 ... -0.36495848 -0.11874088
  -0.92357635]
 [ 0.63696648  2.35465142 -0.02132963 ... -0.11878075 -0.44660188
  -0.20654489]
 ...
 [-0.83069822  0.91036893 -0.13740926 ... -0.32608831 -0.37634595
   0.66982688]
 [-0.53716528  1.0987536  -1.06604632 ...  0.89184359 -0.74100768
  -0.68456586]
 [ 0.63696648 -0.65950334 -0.60172779 ... -0.63704964  0.11879107
  -0.12687473]]


Apply KNN classifier

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [0]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Confusion Matrix is a performance measurement for machine learning classification problem where output can be two or more classes. It is a table with 4 different combinations of predicted and actual values.
TP, FP, FN, TN



In [0]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[235,  37],
       [ 49,  79]])

In [0]:
from sklearn.metrics import f1_score,accuracy_score
f1_score(y_test,y_pred)
print(accuracy_score(y_test,y_pred)*100)

78.5
