In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import os
path = os.getcwd() +'/data/mnist_train_5000.csv'
data = pd.read_csv(path, header=None)
data.head()

0    1    2    3    4    5    6    7    8    9   ...   775  776  777  778  \
0    5    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
2    4    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
3    1    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
4    9    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 785 columns]

In [4]:
data.describe()

0       1       2       3       4       5       6       7    \
count  5000.00000  5000.0  5000.0  5000.0  5000.0  5000.0  5000.0  5000.0   
mean      4.46700     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       2.87224     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       0.00000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       2.00000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       4.00000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       7.00000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       9.00000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

          8       9     ...            775          776          777  \
count  5000.0  5000.0   ...    5000.000000  5000.000000  5000.000000   
mean      0.0     0.0   ...       0.232200     0.141200     0.062800   
std       0.0     0.0   ...       6.439579     4.843919     3.038405   
min       0.0     0.0   ...       0.000000     0.000000     0.000000   
25%       0.0     0.0   ...       0.000000     0.000000     0.000000   
50%       0.0     0.0   ...       0.000000     0.000000     0.000000   
75%       0.0     0.0   ...       0.000000     0.000000     0.000000   
max       0.0     0.0   ...     254.000000   254.000000   160.000000   

               778          779     780     781     782     783     784  
count  5000.000000  5000.000000  5000.0  5000.0  5000.0  5000.0  5000.0  
mean      0.054000     0.036600     0.0     0.0     0.0     0.0     0.0  
std       2.805398     1.910704     0.0     0.0     0.0     0.0     0.0  
min       0.000000     0.000000     0.0     0.0     0.0     0.0     0.0  
25%       0.000000     0.000000     0.0     0.0     0.0     0.0     0.0  
50%       0.000000     0.000000     0.0     0.0     0.0     0.0     0.0  
75%       0.000000     0.000000     0.0     0.0     0.0     0.0     0.0  
max     187.000000   119.000000     0.0     0.0     0.0     0.0     0.0  

[8 rows x 785 columns]

In [5]:
data.shape

(5000, 785)

In [6]:
cols=data.shape[1]
print("columns = {}".format(cols))

columns = 785


In [7]:
y=np.array(data.iloc[:,:1])

In [8]:
print(y)

[[5]
 [0]
 [4]
 ..., 
 [2]
 [1]
 [2]]


In [9]:
x=np.array(data.iloc[:,1:cols])
print(x)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [10]:
x.shape, y.shape

((5000, 784), (5000, 1))

In [11]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [12]:
rows = x.shape[0]
params = x.shape[1]
classes = 4
all_theta = np.zeros((classes, params + 1)) 

x = np.insert(x, 0, values=np.ones(rows), axis=1) 

theta = np.zeros(params + 1) 

x.shape, theta.shape, all_theta.shape

((5000, 785), (785,), (4, 785))

In [13]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [14]:
def Computecost(theta, x, y, learning_rate, RegRate):
    theta = np.matrix(theta)
    x = np.matrix(x)
    y = np.matrix(y)
    
    first = np.multiply(-y, np.log(sigmoid(x * theta.T))) #(-y*log(g(z)))
    second = np.multiply((1 - y), np.log(1 - sigmoid(x * theta.T))) #((1-y)*(1-log(g(z))))
    
    reg = (RegRate / 2 * len(x)) * np.sum(np.power(theta[:,1:theta.shape[1]], 2)) #regularisation
    
    return np.sum(first - second) / (len(x)) + reg 

In [15]:
def gradientReg(theta, x, y, learning_rate, RegRate):
    
    theta = np.matrix(theta)
    x = np.matrix(x)
    y = np.matrix(y)
    
    #parameters = int(theta.shape[1])
    
    error = sigmoid(x * theta.T) - y
    grad = ((x.T * error) / len(x)).T
    grad = grad * learning_rate
    grad = grad + ((RegRate / len(x)) * theta)
    
    # intercept gradient is not regularized
    grad[0, 0] = np.sum(np.multiply(error, x[:,0])) / len(x)
    
    return np.array(grad).ravel()

In [16]:
def gradientDescent(x, y, theta, learning_rate, RegRate):
    theta = np.matrix(theta)
    x = np.matrix(x)
    y = np.matrix(y)
    iters = 10000
    params = int(theta.shape[1])
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = (sigmoid(x*theta.T)) - y
        
        for j in range(1, params):
            grad = np.multiply(error, x[:,j])
            theta[0,j] = theta[0,j] - (((learning_rate / len(x)) * np.sum(grad)) + ((RegRate / len(x)) * theta[0,j]))
            
            # intercept gradient is not regularized
            theta[0, 0] = theta[0,0]- (learning_rate * np.sum(np.multiply(error, x[:,0])) / len(x))
           
        #theta = np.array(grad).ravel()
        #cost[i]=Computecost(theta, x, y, learning_rate, RegRate)
        #print("cost ={}".format(cost))
        
    return theta

In [17]:
def one_vs_all(x, y, classes, learning_rate, RegRate,new_theta):
    params = x.shape[1]
    rows = x.shape[0]
      
    for i in range(0, classes):
        theta = new_theta[i,:]
        y_i = np.array([1 if label == i else 0 for label in y])
        y_i = np.reshape(y_i, (rows, 1))
        
        print("class = {}".format(i))
        
        # minimize the objective function
        all_theta[i,:] = gradientDescent(x, y_i, theta, learning_rate, RegRate)
            
    return all_theta

In [18]:
def predict_all(x, theta): 
   
    # convert to matrices
    x = np.matrix(x)
    theta = np.matrix(theta)
    
    # compute the class probability for each class on each training instance
    h = sigmoid(x * theta.T)
    
    # create array of the index with the maximum probability
    h_argmax = np.argmax(h, axis=1)
  
    return h_argmax

In [19]:
test_path = os.getcwd() +'/data/mnist_test.csv'
test_data = pd.read_csv(path, header=None)

In [20]:
##seperate x from the test data
test_cols=test_data.shape[1]
test_x=np.array(test_data.iloc[:,1:test_cols])

In [21]:
##inserting ones in the input
test_rows=test_x.shape[0]
test_x = np.insert(test_x, 0, values=np.ones(test_rows), axis=1)

In [22]:
##seperate y from the test data
test_y=np.array(test_data.iloc[:,:1])
np.unique(test_y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [ ]:
def frange(start, stop, step):
    i = start
    while i < stop:
        yield i
        i = i*step
        

In [ ]:
Learning_rate=1
classes = 4
#Reg_rate = 0.001
for i in frange(0.001, 1, 10):
    new_theta = one_vs_all(x, y, classes, Learning_rate, i, all_theta)
  
    y_pred = predict_all(x, new_theta)
    correct = [1 if a == b else 0 for (a, b) in zip(y_pred, y)]
    accuracy = (sum(map(int, correct)) / float(len(correct)))
    print("i={}".format(i))
    print ("Training data={} %".format(accuracy * 100))
        
    ty_pred = predict_all(test_x, new_theta)
    tcorrect = [1 if a == b else 0 for (a, b) in zip(ty_pred, test_y)]
    taccuracy = (sum(map(int, tcorrect)) / float(len(tcorrect)))
    print ("Test data=""{} %".format(taccuracy * 100))

class = 0


D:\Softwares\ML Software\Old\Lema Labs ML Workshop x64\Lema Labs ML Workshop x64\python-3.6.3.amd64\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
